title: "jonasjberg"
description: >
  These are my thoughts on software development,
  analog circuit design and embedded systems.
author: "Jonas Sjöberg"

url: ""             # the base hostname & protocol for your site
baseurl: ""         # the subpath of your site, e.g. /blog/

email: jomeganas@gmail.com
twitter_username: jonasjberg
github_username:  jonasjberg

# markdown: kramdown
# kramdown:
#   input: GFM

sass:
    sass_dir: _sass


# "Bind HTTP server to all available IPs, rather than just to localhost.
#  GitHub will simply ignore this when pushing, so it's safe to use if you
#  don't mind having your work openly accessible on your network."
# http://stackoverflow.com/a/16608698
host: 0.0.0.0
