title: "jonasjberg"
description: >
  These are my thoughts on software development,
  analog circuit design and embedded systems.
author: "Jonas Sjöberg"

url: ""             # the base hostname & protocol for your site
baseurl: ""         # the subpath of your site, e.g. /blog/

email: jomeganas@gmail.com
twitter_username: jonasjberg
github_username:  jonasjberg

markdown: kramdown

sass:
    sass_dir: _sass
