locale: eng-US
title: "jonasjberg"
description: >
  These are my thoughts on software development,
  analog circuit design and embedded systems.
author: "Jonas Sjöberg"
email: jomeganas@gmail.com
country: Northern Sweden

url: https://jonasjberg.github.io
baseurl: ""         # the subpath of your site, e.g. /blog/
site: jonasjberg.github.io

twitter_username: jonasjberg
github_username:  jonasjberg
linkedin_username:
google_plus_username:
facebook_username: jonasjbrg
dribbble_username:
instagram_username: jonasjberg

defaultimage: "https://avatars0.githubusercontent.com/u/5494704?v=3&s=460"

# markdown: kramdown
# kramdown:
#   input: GFM

sass:
    sass_dir: _sass


# "Bind HTTP server to all available IPs, rather than just to localhost.
#  GitHub will simply ignore this when pushing, so it's safe to use if you
#  don't mind having your work openly accessible on your network."
# http://stackoverflow.com/a/16608698
host: 0.0.0.0
